#Lara Willson
#This Program works as a MadLib and uses the user's words to fill in blanks within a story.

print('Hey There! You look like someone who likes stories which is great because I have loads of stories to share.')
print('There is one problem though - I seem to have forgotten some of the words in the stories I like to tell (I guess I should have taken notes along the way).')
print('But you look like you could help!')
print('Let’s start by selecting what type of story we should tell:')

#Here are the genre options
print('1. Superhero')
print('2. Action')
print('3. Adventure')
print('4. Romance')

#Here we are defining the variable Genre as the user's response
Genre=input()

if int(Genre) > 4 or int(Genre) < 1:
    print('Hey silly, that was not an option. Please choose a number 1-4 to choose a genre')
elif Genre == '1':
    print('Horray I was hoping we would tell a Superhero story. Now first thing is first I need you to help me witha few words. I am going to prompt you with a word type (i.e. noun, name, verb, etc.) and I need you to go ahead and type in the first corresponding word you can think of. Once you have helped me with all of the words you need, I will tell you the whole story.')
    print('First give me Silly Name')
    Silly=input()
    print('An Unrealistic Profession?')
    Profession=input()
    print('Name a Country.')
    Country=input()
    print('Another Silly Name')
    NameTwo=input()
    print('Color')
    Color=input()
    print('Name an Adjective.')
    Adjective=input()
    print('An adverb')
    Adverb=input()
    print('A Silly Female Name')
    NameThree=input()
    print('One More Silly Name')
    NameFour=input()
    print('Name a Facial Feature')
    Feature=input()
    print('This is the Last Silly Name - I swear')
    NameFive=input()
    print('Now for an -ing verb')
    Verb=input()
    print('A City?')
    City=input()
    print('How about a noun?')
    Noun=input()
    print('a Random Actor?')
    Actor=input()
    print('Last but not least - a final Noun')
    NounTwo=input()
    print('Meet our hero ' + Silly + ' a super intelligent ' + Profession + '. A run-in with the ' + Country + 'military leads him to create his alter-ego ' + NameTwo + ' a' + Color + ',' + Adjective + ' giant capable of great destruction. He ' + Adverb + ' battles the military with his girlfriend, ' + NameThree + ' .Eventually it is discovered that our hero’s long-time colleague ' + NameFour + ', distinguished by his ' + Feature + ' is trying to turn ' + Silly + ' into a weapon, leading to a climactic (if pointless) battle in downtown ' + City + ' with an evil version of the same giant alter-ego called ' + NameFive + '. Eventually the enemy is subdued by ' + Verb + ' him with a ' + Noun + '. In the final reel, ' + Actor + ' appears to propose joining him in a ' + NounTwo)
    print('I am so glad you were here to help me tell that story!')
elif Genre == '2':
    print('Horray I was hoping we would tell a Action story. Now first thing is first I need you to help me witha few words. I am going to prompt you with a word type (i.e. noun, name, verb, etc.) and I need you to go ahead and type in the first corresponding word you can think of. Once you have helped me with all of the words you need, I will tell you the whole story.')
    print('Give me a male name')
    Man=input()
    print('An occupation?')
    Job=input()
    print('How about a noun?')
    Noun=input()
    print('Another noun')
    NounTwo=input()
    print('One more noun')
    NounThree=input()
    print('A shape?')
    Shape=input()
    print('A Verb')
    Verb=input()
    print('How about a female name?')
    Girl=input()
    print('Body Part')
    Body=input()
    print('Another Verb')
    VerbTwo=input()
    print('A noun?')
    NounFour=input()
    print('Another noun?')
    NounFive=input()
    print('Restaurant Name')
    Restaurant=input()
    print('A Historic Monunment?')
    Monument=input()
    print('A Verb')
    VerbTwo=input()
    print('A Noun')
    NounSix=input()
    print('Another Noun')
    NounSeven=input()
    print('A Noun')
    NounEight=input()
    print('A Verb?')
    VerbThree=input()
    print('I just cannot remember nouns - how about another one?')
    NounNine=input()
    print('An Adjective?')
    Adjective=input()
    print('Another Adjective?')
    AdjectiveTwo=input()
    print('An Emotion?')
    Emotion=input()
    print('An Ing Verb')
    IngVerb=input()
    print('A Noun')
    NounTen=input()
    print('Another Noun')
    NounEleven=input()
    print('One last verb')
    VerbFour=input()
    print(Man + ' is a normal ' + Job + '. Then, one day, a ' + Noun + ' explodes, causing a ' + NounTwo + ' to blow up, and a nearby ' + NounThree +' erupts into a ' + Shape + ' of flames. ' + Man + ' realizes that he’s being chased by the government, who’s trying to ' + Verb +' him. While on the run, he teams up with an incredibly attractive woman named ' + Girl + ', who has an incredible ' + Body + '. She may be from the streets but she can ' + VerbTwo + ' like nobody’s business. The duo decide to turn the tables on their pursuers by blowing up a ' + NounFour + ' , which triggers a chain reaction, causing the local ' + NounFive + ',' + Restaurant + ', and the ' + Monument + ' to explode. Then, the bad guys; helicopter gets ' + VerbTwo + ' by a piece of ' + NounSix + ' from when the ' + NounSeven + ' exploded, and the helicopter explodes and falls onto a ' + NounEight + ' , causing it to ' + VerbThree + ', which shoots a fireball straight into the hears of ' + NounNine + ' and destroyed the bad guy leader. Everything is ' + Adjective + ' and the two decide that such a ' + AdjectiveTwo + ' ordeal has caused them to fall in ' + Emotion + ' with each other. They decide to celebrate by ' + IngVerb + ' on the ' + NounTen + ', and they even managed to use a ' + NounEleven + ' from the beginning of the movie, to ' + VerbFour + ' the whole story together.')
    print('I am so glad you were here to help me tell that story!')
elif Genre == '3':
    print('Horray I was hoping we would tell a Adventure story. Now first thing is first I need you to help me witha few words. I am going to prompt you with a word type (i.e. noun, name, verb, etc.) and I need you to go ahead and type in the first corresponding word you can think of. Once you have helped me with all of the words you need, I will tell you the whole story.')
    print('Name a type of watercraft')
    Watercraft=input()
    print('What about a plural noun?')
    Plural=input()
    print('A Last Name?')
    Last=input()
    print('A Plural Noun')
    Plural=input()
    print('Another Plural Noun')
    PluralTwo=input()
    print('One Last Plural Noun')
    PluralThree=input()
    print('An adjective')
    Adjective=input()
    print('A Noun')
    Noun=input()
    print('Past Tense Verb')
    Past=input()
    print('Another Adjective')
    AdjectiveTwo=input()
    print('The name of a Song')
    Song=input()
    print('Female Name')
    Girl=input()
    print('Male Name')
    Guy=input()
    print('An Adjective')
    AdjectiveThree=input()
    print('Singular Noun')
    NounTwo=input()
    print('A Famous Person')
    Famous=input()
    print('Another Noun')
    NounThree=input()
    print('A Large Number?')
    Number=input()
    print('Another Number')
    NumberTwo=input()
    print('One Last Noun')
    NounFour=input()
    print('The ' + Watercraft + ' Lucky Lulu was sinking quickly. “Abandon ship! Everyone into the ' + Plural + '!” hollered Captain ' + Last + '. But the crew and passengers knew there were not enough ' + Plural + ', so they threw ' + PluralTwo + ',' + PluralThree + ', and even one ' + Adjective + Noun + ' overboard. Then everyone ' + Past + ' into the ' + AdjectiveTwo + ' water and grabbed onto whatever they could.Captain ' + Last + ' ordered everyone to form a line, tie their crafts together, and sing ' + Song + '. First in line were ' + Girl + ' and ' + Guy + ', bobbing in their ' + AdjectiveThree + NounTwo + '. Next, came ' + Famous + ' hanging on for dear life to a slimy ' + NounThree + '. They were followed by ' + Number + ' others. After ' + NumberTwo + ' days, they were rescued by a strange ' + NounFour + '. Not one passenger from the Lucky Lulu has gone back out on the water.')
    print('I am so glad you were here to help me tell that story!')
elif Genre == '4':
    print('Horray I was hoping we would tell a Romance story. Now first thing is first I need you to help me witha few words. I am going to prompt you with a word type (i.e. noun, name, verb, etc.) and I need you to go ahead and type in the first corresponding word you can think of. Once you have helped me with all of the words you need, I will tell you the whole story.')
    print('Name a Place')
    Place=input()
    print('Now name some other place')
    PlaceTwo=input()
    print('Now how about a food')
    Food=input()
    print('Another Food')
    FoodTwo=input()
    print('How about a plural food')
    PluralFood=input()
    print('Name a Famous Person')
    Famous=input()
    print('A Noun?')
    Noun=input()
    print('Verb?')
    Verb=input()
    print('Give me a plural noun')
    PluralNoun=input()
    print('An Instrument?')
    Instrument=input()
    print('A plural animal?')
    PluralAnimal=input()
    print('An Adjective')
    Adjective=input()
    print('Another adjective please?')
    AdjectiveTwo=input()
    print('Another Food')
    FoodFour=input()
    print('A Color?')
    Color=input()
    print('Another Color?')
    ColorTwo=input()
    print('How about another noun?')
    NounTwo=input()
    print('A Body Part?')
    Body=input()
    print('A transportation vehicle?')
    Transportation=input()
    print('How about a liquid?')
    Liquid=input()
    print('Another Place?')
    PlaceThree=input()
    print('Give me an exclamation.')
    Exclam=input()
    print('Now I need an adverb')
    Adverb=input()
    print('Last but not least - a verb')
    Verb=input()
    print('Today my best friend and I are going on a double date with two guys we met at ' + Place + '. We were all meeting at ' + PlaceTwo + ' for a picnic. I brought my homemade ' + Food + ' salad and fresh baked ' + FoodTwo +' chip '+ PluralFood + ', that is sure to impress my date, '+ Famous + '. My best friend put a '+ Noun + ' out for all of us to ' + Verb + ' on. We all started talking about ' + PluralNoun +'. My best friends date pulled out his '+ Instrument + ' and started playing us a tune, that is when ' + PluralAnimal + ' started coming right up to us, they were sooo '+ Adjective +' and ' +AdjectiveTwo + 'But as we finished our piece of '+ FoodFour + ' cream pie, a huge ' + Color + ' cloud hoovered over us and a bolt of bright '+ ColorTwo + ' lightning struck down and hit my best friends ' + NounTwo + '. We had to escape right then and there, my date grabbed my '+ Body + ' as we ran for his ' + Transportation + 'cold ' + Liquid + ' started pouring down, my best friend and her date had already gone but she left me a text message that said Meet us at ' + PlaceThree + ', so I texted back ' + Exclam + '. The day ended '+ Adverb + ' with a kiss and a long ' + Verb + '. We all made plans to do it again next weekend ')
    print('I am so glad you were here to help me tell that story!')

#Here we are asking the user to exit the program. Since it is in a while loop, if the user does not enter exit, the program will complain it wants to go back to sleep and prompt the user for an answer again. 
   
import sys
    
while True:
    print('Type exit to exit.')
    answer = input()
    if answer == 'exit':
        sys.exit()
    print('Just let me go back to sleep already.')
